import React, { useState } from "react";
import { 
  Mail, MessageCircle, Phone, Layers, Sparkles, Edit3, Send, Eye,
  BarChart3, TrendingUp, RefreshCw, Wand2, Scissors, Dna, Play,
  Users, Terminal
} from "lucide-react";
import { useOrbit } from "../context/OrbitContext";
import { PageHeaderHUD } from "../components/PageHeaderHUD";
import { AgentCardModal } from "../components/AgentCardModal";

type ChannelType = "Email" | "WhatsApp" | "SMS" | "RCS";
type VariantType = "A" | "B";

interface CampaignTemplate {
  subject?: string;
  body: string;
  title?: string;
  mediaUrl?: string;
}

type CampaignVariants = Record<VariantType, CampaignTemplate>;
type ChannelTemplates = Record<ChannelType, CampaignVariants>;

const INITIAL_TEMPLATES: ChannelTemplates = {
  Email: {
    A: {
      subject: "Exclusive Access: Elevate Your Setup",
      body: "Hello {{name}},\n\nYour journey with ORBIT continues. We are opening priority booking access to the all-new Neural Implant v4 upgrades — customized by our AI agents specifically to match your profile.\n\nYour personalized offer is ready for claim.\n\nClaim priority bookings →\n\nBest,\nOrbit Intelligence Network",
    },
    B: {
      subject: "Urgent: Priority booking slots closing",
      body: "Hello {{name}},\n\nOnly a few slots remain in your cohort's Neural Upgrade launch. Vega predicted high session utility values for your profile.\n\nSecure your upgrade tonight before allocation closes.\n\nClaim your upgrade now →\n\nBest,\nOrbit Intelligence Network",
    }
  },
  WhatsApp: {
    A: {
      body: "⚡ *ORBIT* ⚡\n\nHey {{name}}, ready to upgrade your setup?\n\nWe've unlocked priority access to the new Quantum Implants v2 based on your past activity.\n\nTap here to claim: https://orbit.io/up\n\n_(Reply STOP to opt out)_",
    },
    B: {
      body: "⚡ *URGENT UPDATE* ⚡\n\nHey {{name}}, booking slots are closing fast.\n\nVega calculated 94% affinity for this release. Your priority link expires tonight.\n\nSecure your slot now: https://orbit.io/up\n\n_(Reply STOP to opt out)_",
    }
  },
  SMS: {
    A: {
      body: "ORBIT: Hi {{name}}, your priority access to the new Quantum Deck is active. Book now: https://orbit.io/q",
    },
    B: {
      body: "ORBIT: {{name}}, only 4 spots left in your cohort launch. Slot expires tonight. Secure priority: https://orbit.io/q",
    }
  },
  RCS: {
    A: {
      title: "Elevate Your Setup",
      body: "Hey {{name}}, get exclusive early access to the Cyberwear Implant v4. Interactive booking inside.",
      mediaUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    },
    B: {
      title: "Urgent Upgrade Slots Active",
      body: "Hey {{name}}, Vega predicted high interest in this launch. Only a few priority cards remain. Tap below to book.",
      mediaUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
    }
  }
};

const channelConfig: Record<ChannelType, { icon: React.FC<any>; color: string; border: string; label: string; desc: string }> = {
  Email: { icon: Mail, color: "text-orbit-blue", border: "border-orbit-blue/30 bg-orbit-blue/5", label: "Email Campaign", desc: "HTML template body" },
  WhatsApp: { icon: MessageCircle, color: "text-orbit-success", border: "border-orbit-success/30 bg-orbit-success/5", label: "WhatsApp Blast", desc: "Conversational text blast" },
  SMS: { icon: Phone, color: "text-yellow-400", border: "border-yellow-400/20 bg-yellow-400/5", label: "SMS Campaign", desc: "160 char · link-driven" },
  RCS: { icon: Layers, color: "text-orbit-purple", border: "border-orbit-purple/30 bg-orbit-purple/5", label: "RCS Rich Card", desc: "Interactive media card" },
};

export const GrowthEngine: React.FC = () => {
  const { startMission, launchMissionCampaign, mission } = useOrbit();
  const [activeChannel, setActiveChannel] = useState<ChannelType>("Email");
  const [activeVariant, setActiveVariant] = useState<VariantType>("A");
  const [goal, setGoal] = useState("Increase repeat purchases");
  const [content, setContent] = useState<ChannelTemplates>(INITIAL_TEMPLATES);
  const [isPreview, setIsPreview] = useState(false);
  const [selectedAgent, setSelectedAgent] = useState<"Polaris" | "Vega" | "Nova" | "Atlas" | "Luna" | null>(null);

  /* AI loading & generation state */
  const [isGenerating, setIsGenerating] = useState(false);

  /* Performance KPIs (Generated by AI) */
  const [audienceSize, setAudienceSize] = useState(24);
  const [expectedRoi, setExpectedRoi] = useState(4.2);
  const [expectedRevenue, setExpectedRevenue] = useState(68400);

  /* Mission Simulator States */
  const [isSimulating, setIsSimulating] = useState(false);
  const [simLogs, setSimLogs] = useState<string[]>([]);
  const [simProgress, setSimProgress] = useState(0);

  /* Handle manual input edits */
  const handleBodyChange = (val: string) => {
    setContent(prev => ({
      ...prev,
      [activeChannel]: {
        ...prev[activeChannel],
        [activeVariant]: {
          ...prev[activeChannel][activeVariant],
          body: val
        }
      }
    }));
  };

  const handleSubjectChange = (val: string) => {
    setContent(prev => ({
      ...prev,
      Email: {
        ...prev.Email,
        [activeVariant]: {
          ...prev.Email[activeVariant],
          subject: val
        }
      }
    }));
  };

  const handleTitleChange = (val: string) => {
    setContent(prev => ({
      ...prev,
      RCS: {
        ...prev.RCS,
        [activeVariant]: {
          ...prev.RCS[activeVariant],
          title: val
        }
      }
    }));
  };

  /* AI Copywriting Assists (Notion style) */
  const handleAIAssist = (action: "shorter" | "dna" | "improve") => {
    const currentText = content[activeChannel][activeVariant].body;
    let newText = currentText;

    if (action === "shorter") {
      newText = currentText.split("\n\n").slice(0, 2).join("\n\n") + "\n\nClaim priority offer now →";
    } else if (action === "dna") {
      newText = currentText.replace("Hello {{name}},", "Hello {{name}},\n\n[DNA: Tech Enthusiast] node parameters active.");
    } else if (action === "improve") {
      newText = `Dear {{name}},\n\nWe have identified optimal performance parameters matching your session profiles. To maximize system utility, priority bookings are now active.\n\nSelect upgrades: https://orbit.io/up`;
    }

    setContent(prev => ({
      ...prev,
      [activeChannel]: {
        ...prev[activeChannel],
        [activeVariant]: {
          ...prev[activeChannel][activeVariant],
          body: newText
        }
      }
    }));
  };

  /* AI Campaign Generator execution */
  const handleAIGenerate = () => {
    setIsGenerating(true);
    // Simulate generation delay
    setTimeout(() => {
      setIsGenerating(false);
      // Adjust KPIs based on keywords
      const isChurn = goal.toLowerCase().includes("churn") || goal.toLowerCase().includes("retention");
      if (isChurn) {
        setAudienceSize(18);
        setExpectedRoi(5.4);
        setExpectedRevenue(85000);
      } else {
        setAudienceSize(24);
        setExpectedRoi(4.2);
        setExpectedRevenue(68400);
      }
      // Trigger mission context logs
      startMission(goal);
    }, 2000);
  };

  /* Mission Simulator execution */
  const runSimulator = () => {
    setIsSimulating(true);
    setSimProgress(0);
    setSimLogs([]);

    const steps = [
      { t: 0, msg: "Initializing Atlas simulator engine... [ NOMINAL ]" },
      { t: 800, msg: "Connecting to Polaris customer database..." },
      { t: 1500, msg: `Scanning indexes... Found ${audienceSize} customer targets` },
      { t: 2200, msg: `Mapping creatives: Variant ${activeVariant} (${activeChannel})` },
      { t: 3000, msg: "Simulating delivery webhook pathways..." },
      { t: 3800, msg: `Complete. Deliveries: 98% | Open: 75% | Clicks: 32%` },
      { t: 4500, msg: `Expected converted purchases: ${Math.round(audienceSize * 0.28)}. Predicted yield: ₹${expectedRevenue.toLocaleString()}.` }
    ];

    steps.forEach((step, idx) => {
      setTimeout(() => {
        setSimLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${step.msg}`]);
        setSimProgress(Math.round(((idx + 1) / steps.length) * 100));
        if (idx === steps.length - 1) {
          setIsSimulating(false);
        }
      }, step.t);
    });
  };

  const currentTemplate = content[activeChannel][activeVariant];

  return (
    <div className="flex-1 flex overflow-hidden bg-[#050816] relative">
      {/* Background Matrix overlays */}
      <div className="pointer-events-none absolute inset-0 space-grid opacity-35 z-0" />
      <div className="pointer-events-none absolute inset-0 bg-orbit-glow-blue opacity-15 z-0" />

      {/* ════════════════════════════════════════
          LEFT PANEL — GOAL & METRICS
      ════════════════════════════════════════ */}
      <aside className="w-64 shrink-0 flex flex-col border-r border-gray-800/60 bg-gray-950/45 backdrop-blur-md p-4 space-y-4 overflow-y-auto relative z-10">
        {/* Goal Input panel */}
        <div className="orbit-panel p-4 border border-gray-850 bg-gray-900/10 space-y-3 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-16 h-16 bg-orbit-glow-blue opacity-25 pointer-events-none" />
          <h2 className="font-space text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-gray-800/60 pb-2">
            <Sparkles size={13} className="text-orbit-purple" />
            AI Directive
          </h2>
          <div className="space-y-3">
            <div>
              <label className="font-mono text-[8px] text-gray-550 uppercase tracking-wider block mb-1">Business Goal</label>
              <textarea
                rows={3}
                value={goal}
                onChange={e => setGoal(e.target.value)}
                className="w-full bg-gray-950 border border-gray-800 rounded-lg p-2 font-mono text-[10px] text-white focus:outline-none focus:border-blue-500/50 resize-none leading-relaxed"
                placeholder="e.g. Increase repeat purchases..."
              />
            </div>
            
            <button
              onClick={handleAIGenerate}
              disabled={isGenerating || !goal.trim()}
              className={`w-full py-2.5 rounded-xl text-xs font-mono font-bold uppercase tracking-wider flex items-center justify-center gap-2 transition-all cursor-pointer ${
                isGenerating
                  ? "bg-gray-850 text-gray-550 border border-gray-800 cursor-not-allowed"
                  : "bg-gradient-to-r from-orbit-blue to-orbit-purple text-white shadow-orbit-glow hover:opacity-90 hover:scale-[1.02] active:scale-95 duration-200"
              }`}
            >
              {isGenerating ? <RefreshCw size={12} className="animate-spin" /> : <Wand2 size={12} />}
              {isGenerating ? "Analyzing..." : "AI Generate Campaign"}
            </button>
          </div>
        </div>

        {/* ROI Forecast Metrics */}
        <div className="orbit-panel p-4 border border-gray-850 bg-gray-900/10 space-y-4">
          <h3 className="font-space text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-gray-800/60 pb-2">
            <BarChart3 size={13} className="text-orbit-success" />
            Predicted Results
          </h3>

          <div className="space-y-3.5 font-mono">
            <div className="bg-gray-950/40 p-2.5 rounded-lg border border-gray-900 flex items-center justify-between">
              <div>
                <span className="text-[8px] text-gray-550 uppercase block">Expected Yield</span>
                <span className="text-sm font-bold text-white">₹{expectedRevenue.toLocaleString()}</span>
              </div>
              <TrendingUp size={16} className="text-orbit-success animate-pulse" />
            </div>

            <div className="grid grid-cols-2 gap-2">
              <div className="bg-gray-950/40 p-2 rounded-lg border border-gray-900">
                <span className="text-[8px] text-gray-550 uppercase block">Target Cohort</span>
                <span className="text-xs font-bold text-white">{audienceSize} stars</span>
              </div>
              <div className="bg-gray-950/40 p-2 rounded-lg border border-gray-900">
                <span className="text-[8px] text-gray-550 uppercase block">Expected ROI</span>
                <span className="text-xs font-bold text-orbit-success">{expectedRoi}x</span>
              </div>
            </div>

            {/* Micro progress graph */}
            <div className="space-y-1">
              <div className="flex justify-between text-[8px] text-gray-500">
                <span>Model Confidence</span>
                <span>87%</span>
              </div>
              <div className="w-full h-1 bg-gray-900 rounded-full overflow-hidden">
                <div className="h-full bg-orbit-success rounded-full" style={{ width: "87%" }} />
              </div>
            </div>
          </div>
        </div>

        {/* Audience insights */}
        <div className="orbit-panel p-4 border border-gray-850 bg-gray-900/10 space-y-3 flex-1">
          <h3 className="font-space text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-gray-800/60 pb-2">
            <Users size={13} className="text-yellow-450" />
            Audience Insights
          </h3>
          
          <div className="space-y-2.5 font-mono text-[9px]">
            <div className="flex justify-between text-gray-500">
              <span>Primary DNA Segment:</span>
              <span className="text-white font-semibold">Loyalists (Tech)</span>
            </div>
            <div className="flex justify-between text-gray-500">
              <span>Optimal Channel Node:</span>
              <span className="text-orbit-success font-semibold">WhatsApp</span>
            </div>
            <div className="flex justify-between text-gray-500 border-t border-gray-900 pt-2 mt-2">
              <span>Avg Risk factor:</span>
              <span className="text-gray-300">12% Churn</span>
            </div>
            <div className="flex justify-between text-gray-500">
              <span>Avg LTV baseline:</span>
              <span className="text-gray-300">₹3,400</span>
            </div>
          </div>
        </div>
      </aside>

      {/* ════════════════════════════════════════
          CENTER PANEL — WORKSPACE & EDITOR
      ════════════════════════════════════════ */}
      <main className="flex-1 flex flex-col min-w-0 overflow-hidden relative z-10 border-r border-gray-800/60">
        <div className="shrink-0 px-6 pt-4 bg-gray-950/20">
          <PageHeaderHUD
            title="Growth Engine"
            subtitle="AUTONOMOUS CAMPAIGN CONSTRUCTOR & COPYWRITING LAB"
            onSelectAgent={setSelectedAgent}
          />
        </div>

        {/* Channel selector top bar */}
        <div className="shrink-0 p-3 bg-gray-950/20 border-b border-gray-900/60 grid grid-cols-4 gap-2">
          {(Object.entries(channelConfig) as [ChannelType, typeof channelConfig[ChannelType]][]).map(([ch, cfg]) => {
            const Icon = cfg.icon;
            const isActive = activeChannel === ch;
            return (
              <button
                key={ch}
                onClick={() => {
                  setActiveChannel(ch);
                  setIsPreview(false);
                }}
                className={`flex items-center gap-2 p-2 rounded-xl border text-left cursor-pointer transition-all duration-200 ${
                  isActive 
                    ? `${cfg.border} ${cfg.color} shadow-[0_0_15px_rgba(59,130,246,0.05)]` 
                    : "border-gray-900 bg-transparent text-gray-500 hover:border-gray-800 hover:text-gray-300"
                }`}
              >
                <Icon size={14} className="shrink-0" />
                <div className="min-w-0">
                  <p className="text-[10px] font-bold font-space truncate">{cfg.label.split(" ")[0]}</p>
                </div>
              </button>
            );
          })}
        </div>

        {/* Editor workspace container */}
        <div className="flex-1 flex flex-col p-6 space-y-4 overflow-y-auto">
          {/* Header row: edit/preview + Variant tabs */}
          <div className="flex items-center justify-between border-b border-gray-900 pb-3">
            {/* A/B Testing Variant Tabs */}
            <div className="flex items-center gap-1 bg-gray-950 p-1 rounded-xl border border-gray-900 font-mono text-[9px] font-bold">
              <button
                onClick={() => setActiveVariant("A")}
                className={`px-3 py-1 rounded-lg cursor-pointer transition-all ${
                  activeVariant === "A" 
                    ? "bg-gray-850 text-white border border-gray-800 shadow" 
                    : "text-gray-500 hover:text-gray-300"
                }`}
              >
                Variant A (Classic)
              </button>
              <button
                onClick={() => setActiveVariant("B")}
                className={`px-3 py-1 rounded-lg cursor-pointer transition-all ${
                  activeVariant === "B" 
                    ? "bg-gray-855 text-white border border-gray-800 shadow" 
                    : "text-gray-500 hover:text-gray-300"
                }`}
              >
                Variant B (AI Urgent)
              </button>
            </div>

            {/* Edit / Preview controls */}
            <div className="flex items-center gap-2">
              <button
                onClick={() => setIsPreview(false)}
                className={`px-3 py-1.5 rounded-lg text-[10px] font-mono border transition-all flex items-center gap-1.5 cursor-pointer ${
                  !isPreview 
                    ? "border-orbit-blue/30 bg-orbit-blue/10 text-orbit-blue" 
                    : "border-gray-900 text-gray-500 hover:border-gray-850 hover:text-gray-300"
                }`}
              >
                <Edit3 size={11} /> Edit
              </button>
              <button
                onClick={() => setIsPreview(true)}
                className={`px-3 py-1.5 rounded-lg text-[10px] font-mono border transition-all flex items-center gap-1.5 cursor-pointer ${
                  isPreview 
                    ? "border-orbit-blue/30 bg-orbit-blue/10 text-orbit-blue" 
                    : "border-gray-900 text-gray-500 hover:border-gray-850 hover:text-gray-300"
                }`}
              >
                <Eye size={11} /> Preview
              </button>
            </div>
          </div>

          {!isPreview ? (
            /* Notion style workspace editor */
            <div className="flex-1 flex flex-col gap-4">
              
              {/* Subject line inputs if Email / RCS */}
              {activeChannel === "Email" && (
                <div className="space-y-1.5">
                  <label className="font-mono text-[9px] text-gray-500 uppercase tracking-wider block">Subject Line</label>
                  <input
                    type="text"
                    value={currentTemplate.subject || ""}
                    onChange={e => handleSubjectChange(e.target.value)}
                    className="w-full bg-gray-950/60 border border-gray-900 rounded-lg px-3 py-2 text-xs font-mono text-white focus:outline-none focus:border-blue-500/50"
                  />
                </div>
              )}
              {activeChannel === "RCS" && (
                <div className="space-y-1.5">
                  <label className="font-mono text-[9px] text-gray-555 uppercase tracking-wider block">Card Title</label>
                  <input
                    type="text"
                    value={currentTemplate.title || ""}
                    onChange={e => handleTitleChange(e.target.value)}
                    className="w-full bg-gray-950/60 border border-gray-900 rounded-lg px-3 py-2 text-xs font-mono text-white focus:outline-none focus:border-blue-500/50"
                  />
                </div>
              )}

              {/* Messaging text area */}
              <div className="flex-1 flex flex-col min-h-[220px]">
                <label className="font-mono text-[9px] text-gray-500 uppercase tracking-wider block mb-1.5">Creative Copy Body</label>
                <textarea
                  value={currentTemplate.body}
                  onChange={e => handleBodyChange(e.target.value)}
                  className="w-full flex-1 bg-gray-950/50 border border-gray-900 rounded-xl p-4 text-xs font-mono text-gray-200 focus:outline-none focus:border-blue-500/50 resize-none leading-relaxed"
                />
              </div>

              {/* Notion AI Style quick rewrite assist panel */}
              <div className="p-3.5 bg-gray-950 border border-gray-900 rounded-xl space-y-2.5">
                <div className="flex items-center gap-1.5">
                  <Sparkles size={12} className="text-orbit-purple" />
                  <span className="font-mono text-[9px] font-bold text-gray-400 uppercase tracking-wider">AI Copywriting Assist</span>
                </div>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => handleAIAssist("shorter")}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-850 bg-gray-900/40 text-gray-300 hover:border-gray-700 font-mono text-[9px] cursor-pointer hover:bg-gray-900 transition-colors"
                  >
                    <Scissors size={10} className="text-gray-500" />
                    Make Shorter
                  </button>
                  <button
                    onClick={() => handleAIAssist("dna")}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-850 bg-gray-900/40 text-gray-300 hover:border-gray-700 font-mono text-[9px] cursor-pointer hover:bg-gray-900 transition-colors"
                  >
                    <Dna size={10} className="text-orbit-purple" />
                    Inject DNA Tags
                  </button>
                  <button
                    onClick={() => handleAIAssist("improve")}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-gray-850 bg-gray-900/40 text-gray-300 hover:border-gray-700 font-mono text-[9px] cursor-pointer hover:bg-gray-900 transition-colors"
                  >
                    <Wand2 size={10} className="text-orbit-success" />
                    Professional Tone
                  </button>
                </div>
              </div>

              <p className="font-mono text-[8px] text-gray-600">
                * Dynamic fields supported: Use &#123;&#123;name&#125;&#125; variables. Nova copywriting node automatically injects values.
              </p>
            </div>
          ) : (
            /* Canva style visual preview workspace */
            <div className="flex-1 flex flex-col items-center justify-center py-6 bg-gray-950/20 rounded-xl border border-gray-900 relative overflow-hidden">
              <div className="absolute inset-0 space-grid opacity-15 pointer-events-none" />
              
              {activeChannel === "Email" && (
                <div className="w-full max-w-md bg-white text-gray-900 rounded-2xl overflow-hidden shadow-2xl border border-gray-200 font-sans text-xs">
                  <div className="bg-gradient-to-r from-blue-600 to-purple-600 px-5 py-3">
                    <div className="text-white text-[9px] opacity-70 font-mono mb-0.5">From: ORBIT Intelligence &lt;dispatch@orbit.net&gt;</div>
                    <div className="text-white font-bold text-sm">{currentTemplate.subject}</div>
                  </div>
                  <div className="p-5 whitespace-pre-line text-gray-750 leading-relaxed">{currentTemplate.body.replace("{{name}}", "Arjun")}</div>
                  <div className="px-5 pb-5 flex">
                    <button className="px-5 py-2 bg-blue-600 text-white rounded-lg text-[10px] font-bold hover:bg-blue-700 transition-colors cursor-pointer">Claim priority upgrade →</button>
                  </div>
                </div>
              )}

              {activeChannel === "WhatsApp" && (
                <div className="w-64 bg-[#0a1014] rounded-3xl overflow-hidden p-3 border border-gray-800 shadow-2xl relative">
                  {/* device status bar */}
                  <div className="flex justify-between items-center text-[7px] text-gray-500 font-mono px-2 mb-1.5">
                    <span>11:42 AM</span>
                    <span>98%</span>
                  </div>
                  <div className="bg-[#1f2c34] rounded-2xl p-3">
                    <div className="bg-[#005d4b] text-white rounded-2xl p-2.5 text-[10px] font-sans leading-relaxed whitespace-pre-line shadow-sm border border-emerald-900/20">
                      {currentTemplate.body.replace("{{name}}", "Arjun")}
                    </div>
                    <div className="text-right mt-1 text-[7px] text-gray-550">11:42 AM ✓✓</div>
                  </div>
                </div>
              )}

              {activeChannel === "SMS" && (
                <div className="w-60 bg-gray-950 rounded-2xl p-3 border border-gray-800 shadow-2xl">
                  <div className="bg-blue-650 text-white rounded-2xl p-3 text-[10px] leading-relaxed whitespace-pre-line">
                    {currentTemplate.body.replace("{{name}}", "Arjun")}
                  </div>
                  <div className="text-right text-[7px] text-gray-550 mt-1 font-mono">SMS MESSAGE · DELIVERED</div>
                </div>
              )}

              {activeChannel === "RCS" && (
                <div className="w-64 bg-[#0a1014] rounded-3xl overflow-hidden border border-gray-800 shadow-2xl">
                  {currentTemplate.mediaUrl && (
                    <img src={currentTemplate.mediaUrl} alt="RCS header" className="w-full h-28 object-cover" />
                  )}
                  <div className="p-3.5 space-y-2">
                    <h3 className="font-space font-bold text-white text-xs leading-snug">{currentTemplate.title}</h3>
                    <p className="text-[10px] text-gray-400 leading-relaxed whitespace-pre-line">{currentTemplate.body.replace("{{name}}", "Arjun")}</p>
                    <button className="w-full py-2 bg-orbit-blue text-white rounded-lg text-[10px] font-bold hover:bg-blue-600 cursor-pointer transition-colors mt-2">Explore Upgrades</button>
                  </div>
                </div>
              )}
            </div>
          )}
        </div>
      </main>

      {/* ════════════════════════════════════════
          RIGHT PANEL — LAUNCH & MISSION SIMULATOR
      ════════════════════════════════════════ */}
      <aside className="w-64 shrink-0 flex flex-col bg-gray-950/45 backdrop-blur-md p-4 space-y-4 overflow-y-auto relative z-10">
        
        {/* Mission Simulator Console */}
        <div className="orbit-panel p-3.5 border border-gray-850 bg-gray-900/10 flex flex-col gap-3 flex-1 min-h-[220px]">
          <h3 className="font-space text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-gray-800/60 pb-2">
            <Terminal size={13} className="text-orbit-purple" />
            Mission Simulator
          </h3>
          
          <button
            onClick={runSimulator}
            disabled={isSimulating}
            className={`w-full py-2 rounded-lg font-mono text-[9px] font-bold uppercase tracking-wider flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
              isSimulating
                ? "bg-gray-850 text-gray-550 border border-gray-800 cursor-not-allowed"
                : "bg-gray-900 text-orbit-purple border border-orbit-purple/30 hover:bg-orbit-purple/10 active:scale-95 duration-200"
            }`}
          >
            <Play size={10} />
            Simulate Performance
          </button>

          {/* Simulator Telemetry log output */}
          <div className="flex-1 overflow-y-auto bg-black/60 border border-gray-900 rounded-lg p-2.5 font-mono text-[8px] text-gray-550 space-y-1.5 scrollbar-thin">
            {simLogs.length === 0 ? (
              <p className="text-center py-6 text-gray-650">[ SIMULATOR STANDBY ]</p>
            ) : (
              simLogs.map((log, idx) => (
                <p 
                  key={idx} 
                  className={`leading-relaxed transition-all ${
                    log.includes("Complete") || log.includes("projections") ? "text-green-400 font-bold" : ""
                  }`}
                >
                  {log}
                </p>
              ))
            )}
          </div>

          {/* Progress bar */}
          {isSimulating && (
            <div className="space-y-1 mt-1">
              <div className="flex justify-between text-[7px] font-mono text-gray-550">
                <span>Dispatch Run</span>
                <span>{simProgress}%</span>
              </div>
              <div className="w-full h-1 bg-gray-900 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-orbit-purple rounded-full transition-all duration-300"
                  style={{ width: `${simProgress}%` }}
                />
              </div>
            </div>
          )}
        </div>

        {/* Dispatch launch controls */}
        <div className="orbit-panel p-3.5 border border-gray-850 bg-gray-900/10 space-y-3">
          <h3 className="font-space text-xs font-bold text-white uppercase tracking-wider flex items-center gap-1.5 border-b border-gray-800/60 pb-2">
            <Send size={13} className="text-orbit-success" />
            Launch Controls
          </h3>

          <div className="space-y-2 font-mono text-[9px] text-gray-500">
            <div className="flex justify-between">
              <span>Primary Node:</span>
              <span className="text-white font-bold">{activeChannel}</span>
            </div>
            <div className="flex justify-between">
              <span>Consent Check:</span>
              <span className="text-orbit-success font-bold">VERIFIED</span>
            </div>
            <div className="flex justify-between border-t border-gray-900 pt-2">
              <span>Queue Status:</span>
              <span className="text-blue-400 font-bold animate-pulse">CLEARED</span>
            </div>
          </div>

          <button
            onClick={() => {
              if (mission.isActive && mission.step === "ready") {
                launchMissionCampaign(activeChannel);
                alert(`Campaign dispatched successfully via ${activeChannel}! Check Mission Control to track live engagements.`);
              } else {
                alert(`Please click "AI Generate Campaign" first to target customer cohorts and prepare the dispatch copy.`);
              }
            }}
            className="w-full py-3 rounded-xl bg-gradient-to-r from-orbit-success to-emerald-400 text-white font-mono text-xs font-bold uppercase tracking-wider flex items-center justify-center gap-2 hover:opacity-90 hover:scale-[1.02] active:scale-95 duration-200 cursor-pointer shadow-orbit-glow-green"
          >
            <Send size={13} />
            Confirm Dispatch
          </button>
        </div>

        {/* footer telemetry */}
        <div className="font-mono text-[8px] text-gray-650 flex justify-between">
          <span>PORT: ATLAS-99</span>
          <span>DISPATCH OK</span>
        </div>
      </aside>

      <AgentCardModal agent={selectedAgent} onClose={() => setSelectedAgent(null)} />
    </div>
  );
};
