import type { Persona } from "../context/OrbitContext";

export interface PresetDNA {
  industry: string;
  businessType: string;
  businessModel: string;
  primaryMetric: string;
  secondaryMetric: string;
  revenue: number;
  topCategory: string;
  growthRate: number;
  riskAreas: string[];
  opportunities: string[];
  personas: Omit<Persona, "id" | "avatar" | "averageSpend" | "predictedLtv" | "riskScore" | "customerCount" | "revenueContributionPct" | "revenuePotential" | "preferredChannel" | "loyaltyScore">[];
}

export const INDUSTRY_PRESETS: Record<string, PresetDNA> = {
  "Fashion & Apparel": {
    industry: "Fashion & Apparel",
    businessType: "Fashion & Apparel Brand",
    businessModel: "D2C Brand & Retail Store",
    primaryMetric: "Revenue",
    secondaryMetric: "Orders",
    revenue: 1450000,
    topCategory: "Oversized Streetwear",
    growthRate: 15,
    riskAreas: ["Mid-season inventory clearance", "Korean fashion oversaturation"],
    opportunities: ["Minimalist utility drop", "Gen Z direct WhatsApp alerts"],
    personas: [
      {
        name: "Student / Gen Z",
        description: "Young trend-focused mobile-first shoppers who respond rapidly to social discovery and visuals.",
        motivation: "Status alignment, aesthetics, peer trends, and instant gratification.",
        buyingPattern: "Mobile-first shopping cycles. Spontaneous checkouts triggered by direct alerts.",
        riskLevel: "Medium",
        purchaseFrequency: "Bi-weekly",
        growthOpportunity: "Deploy visual RCS carousels showcasing trending aesthetics and micro-influencer items.",
        recommendedStrategy: "Send a visual style drop with countdown timers to prompt spontaneous checkouts.",
        whatTheyBuy: "Graphic tees, trending streetwear, mini accessories.",
        whyTheyBuy: "To look on-trend, fit in socially, and experience immediate styling upgrades.",
        whenTheyBuy: "Social feeds scrolling hours, late-night sessions, instant discount drops.",
        bestCommChannel: "Rich RCS carousels with direct click-to-buy links.",
        suggestedCampaign: "Gen Z Streetwear Style Drop (Expected ROI: 4.2x)",
        ageRange: "18 - 24",
        lifestyle: "Digital native, highly active on social media, mobile-first, and value-oriented.",
        buyingTriggers: "Social media visual updates, micro-influencer looks, and checkout coupon code alerts.",
        preferredProducts: "Streetwear, accessories, capsule basics",
        aiInsightsTargeting: "Gen Z represents the future loyalty pipeline. Engaging them with visual assets, social proof, and seamless mobile checkouts maximizes early lifetime value."
      },
      {
        name: "Young Working Professional",
        description: "Fast-paced urban professionals valuing convenience, premium quality, and effortless workwear edits.",
        motivation: "Professional status, styling efficiency, convenience, and build quality.",
        buyingPattern: "Consistently purchases smart-casual fits. High repeat potential on workday drops.",
        riskLevel: "Low",
        purchaseFrequency: "Weekly",
        growthOpportunity: "Bundle styling recommendations to simplify the buying path for professional wear.",
        recommendedStrategy: "Deliver smart workwear edits and payday promotions via Email on Thursday evenings.",
        whatTheyBuy: "Smart blazers, tailored shirts, sleek office trousers.",
        whyTheyBuy: "To express confidence, look professional in the workplace, and save shopping time.",
        whenTheyBuy: "Midday work breaks, Thursday evenings (weekend preparation), and payday windows.",
        bestCommChannel: "Sleek professional HTML email campaigns.",
        suggestedCampaign: "Desk to Dinner Curated Edits (Expected ROI: 4.5x)",
        ageRange: "25 - 34",
        lifestyle: "Fast-paced urban corporate career, balances work-life, values time-saving solutions.",
        buyingTriggers: "Curated workwear alerts, paycheck deposits, convenience shipping options.",
        preferredProducts: "Office wear, smart jackets, utility accessories",
        aiInsightsTargeting: "Professionals have high disposable income but limited time. Streamlining their choice with pre-styled bundles and desktop-friendly email edits drives rapid repeat purchases."
      },
      {
        name: "Homemaker",
        description: "Value-conscious decision makers buying comfortable apparel and versatile family goods.",
        motivation: "Family comfort, versatile wear, product durability, and budgetary savings.",
        buyingPattern: "Occasional bulk purchases. Highly discount-sensitive and tracks clearance calendars.",
        riskLevel: "Medium",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Introduce family bundle coupon drops to increase average cart sizes.",
        recommendedStrategy: "Deliver family bundle offers and loungewear clearance highlights via WhatsApp.",
        whatTheyBuy: "Loungewear sets, versatile denims, kidswear bundles.",
        whyTheyBuy: "To secure comfort, versatility, and high value for the entire household budget.",
        whenTheyBuy: "Morning hours post-commute, mid-season clearance windows, major festival holiday weeks.",
        bestCommChannel: "Conversational WhatsApp catalogs containing copyable coupon alerts.",
        suggestedCampaign: "Family Comfort Loungewear Blast (Expected ROI: 3.8x)",
        ageRange: "35 - 50",
        lifestyle: "Family-centric, runs household logistics, values comfort, versatile fits, and durable products.",
        buyingTriggers: "BOGO coupon alerts, free delivery milestones, clearance calendar notifications.",
        preferredProducts: "Loungewear, comfort denims, family pack bundles",
        aiInsightsTargeting: "Homemakers prioritize value and utility. Re-engaging them with multi-buy discounts and durable everyday wear ensures a stable, recurring revenue line."
      },
      {
        name: "Traditional Buyer",
        description: "High-touch brick-and-mortar loyalists seeking classic heritage pieces and offline fabric quality.",
        motivation: "Fabric authenticity, classic design heritage, and high-touch customer service.",
        buyingPattern: "Infrequent but high-value basket purchases, primarily in physical showrooms.",
        riskLevel: "Low",
        purchaseFrequency: "Quarterly",
        growthOpportunity: "Send direct SMS thali/exhibition invites to bridges physical store visits.",
        recommendedStrategy: "Deploy personalized SMS alerts detailing exclusive store visits and private stock previews.",
        whatTheyBuy: "Heavy silk sarees, linen shirts, classic kurtas, heritage drapes.",
        whyTheyBuy: "To honor traditional dress codes, experience fabric quality, and support local retail.",
        whenTheyBuy: "Wedding season, traditional holidays, private store anniversaries.",
        bestCommChannel: "Direct SMS text notifications with regional helpline links.",
        suggestedCampaign: "Heritage Collection Exclusive Store Preview (Expected ROI: 3.5x)",
        ageRange: "50+",
        lifestyle: "Values traditional aesthetics, slow fashion, offline shopping habits, and personal service.",
        buyingTriggers: "Exhibition alerts, festival discount vouchers, physical callout reminders.",
        preferredProducts: "Silk brocades, premium linens, heritage drapes",
        aiInsightsTargeting: "Traditional buyers have low digital interactions but represent the highest individual basket values. Using SMS to drive them to local outlets preserves high-value offline relationships."
      }
    ]
  },
  "Restaurant": {
    industry: "Restaurant",
    businessType: "Quick Service Restaurant",
    businessModel: "Dine-In + Delivery",
    primaryMetric: "Revenue",
    secondaryMetric: "Orders",
    revenue: 1200000,
    topCategory: "Beverages & Combos",
    growthRate: 18,
    riskAreas: ["Lunch hour staffing bottlenecks", "Slipping weekday dinner traffic"],
    opportunities: ["Corporate lunch box subscriptions", "Weekend brunch combos"],
    personas: [
      {
        name: "Student / Budget Diner",
        description: "Young budget-conscious food lovers looking for pocket-friendly quick meals and late-night snacks.",
        motivation: "Affordable menu options, fast delivery, and social peer meetups.",
        buyingPattern: "Late night orders, mid-afternoon snack checkouts, highly discount-sensitive.",
        riskLevel: "Medium",
        purchaseFrequency: "Weekly",
        growthOpportunity: "WhatsApp coupon codes for late-night menu add-ons and snack drops.",
        recommendedStrategy: "Target with 15% discount menu pushes on WhatsApp between 9 PM and midnight.",
        whatTheyBuy: "Burgers, wraps, soft drinks, milkshakes, french fries.",
        whyTheyBuy: "Affordable craving satisfaction and group study sessions.",
        whenTheyBuy: "Post-college hours, late-night cramming sessions, weekends.",
        bestCommChannel: "WhatsApp alerts with instant copyable coupon codes.",
        suggestedCampaign: "Late Night Cravings Blast (Expected ROI: 4.2x)",
        ageRange: "18 - 24",
        lifestyle: "Student, value-oriented, active during evening/night hours, mobile-first.",
        buyingTriggers: "BOGO coupons, free delivery milestones, late-night reminders.",
        preferredProducts: "Burgers, combos, late-night sides",
        aiInsightsTargeting: "Budget diners buy high volume but low basket sizes. Group thalis or combos increase average ticket size."
      },
      {
        name: "Office Lunch Crowd",
        description: "Corporate employees seeking quick, nutritious, and predictable lunch options during work breaks.",
        motivation: "Speed of service, healthy ingredients, and hassle-free lunch delivery.",
        buyingPattern: "Monday-Friday lunch peaks, bulk office group order checkouts.",
        riskLevel: "Low",
        purchaseFrequency: "Daily",
        growthOpportunity: "Weekly lunch box subscription thalis with free priority delivery.",
        recommendedStrategy: "Deliver email menu reminders at 11:15 AM with corporate group discounts.",
        whatTheyBuy: "Healthy bowls, salads, standard lunch thalis, customized wraps.",
        whyTheyBuy: "Quick desk eats and health-focused meals during tight working schedules.",
        whenTheyBuy: "Workday lunch hours (12:30 PM - 2:00 PM).",
        bestCommChannel: "Email or SMS menu previews at 11:30 AM.",
        suggestedCampaign: "Corporate Lunch Box Express (Expected ROI: 4.5x)",
        ageRange: "25 - 45",
        lifestyle: "Office professional, time-constrained, values nutrition and scheduling consistency.",
        buyingTriggers: "11:30 AM lunch reminders, group order thali discounts.",
        preferredProducts: "Salads, wraps, healthy thalis",
        aiInsightsTargeting: "Office workers value predictability. Pre-ordering options and priority corporate delivery routes capture high repeating volume."
      },
      {
        name: "Family Diners",
        description: "Multi-generational families gathering for high-value weekend dinners and celebration feasts.",
        motivation: "Comfortable seating, kid-friendly options, and premium hospitality.",
        buyingPattern: "Friday-Sunday dinner peaks, table pre-bookings, large orders.",
        riskLevel: "Low",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Anniversary/birthday celebration booking promotions.",
        recommendedStrategy: "Deliver premium WhatsApp reservation invitations with complimentary desserts.",
        whatTheyBuy: "Family platters, premium curries, sharing starters, dessert samplers.",
        whyTheyBuy: "Celebration milestones, bonding, and premium dining experiences.",
        whenTheyBuy: "Weekend dinners, festivals, family birthdays.",
        bestCommChannel: "WhatsApp alerts with table pre-booking links.",
        suggestedCampaign: "Weekend Family Feast Pre-orders (Expected ROI: 3.8x)",
        ageRange: "30 - 55",
        lifestyle: "Family-centric, manages household budget, prioritizes comfortable ambiance.",
        buyingTriggers: "Complimentary birthday treats, premium table reservations, family combo deals.",
        preferredProducts: "Premium curries, bread baskets, mocktails",
        aiInsightsTargeting: "Families represent high average check sizes. Offering early reservation slots and kid-friendly sides increases customer lifetime value."
      },
      {
        name: "Weekend Socialites",
        description: "Aesthetic-focused millennials and Gen Z looking for trendy mocktails and photo-friendly brunch spots.",
        motivation: "Aesthetic interiors, trendy mocktails, social discovery.",
        buyingPattern: "Saturday/Sunday brunch hours, high beverage spend.",
        riskLevel: "High",
        purchaseFrequency: "Bi-weekly",
        growthOpportunity: "Instagram-aligned brunch specials and beverage launch drops.",
        recommendedStrategy: "Deploy rich RCS invitations highlighting new mocktail menus and visual aesthetics.",
        whatTheyBuy: "Artisanal coffee, mocktails, waffle cones, avocado toasts.",
        whyTheyBuy: "To capture photos for social channels, meet peers, and sample trending cafe flavors.",
        whenTheyBuy: "Weekend mornings, mid-day social breaks.",
        bestCommChannel: "RCS visual carousels with chic lifestyle layouts.",
        suggestedCampaign: "Chic Sunday Brunch Drop (Expected ROI: 4.0x)",
        ageRange: "21 - 35",
        lifestyle: "Trendy, active socializer, values experience and plating aesthetics.",
        buyingTriggers: "Visual mocktail previews, new aesthetic menu launches.",
        preferredProducts: "Brewed coffee, artisanal desserts, mocktails",
        aiInsightsTargeting: "Socialites have high brand-sharing potential. Leveraging user-generated content and offering photo-worthy plating yields high organic acquisition."
      }
    ]
  },
  "Gym": {
    industry: "Gym",
    businessType: "Fitness Center",
    businessModel: "Membership Subscriptions",
    primaryMetric: "Active Members",
    secondaryMetric: "Churn Risk",
    revenue: 950000,
    topCategory: "Annual Memberships",
    growthRate: 12,
    riskAreas: ["Summer holiday membership churn", "Low check-in rates"],
    opportunities: ["Corporate wellness bundles", "Personal training onboarding"],
    personas: [
      {
        name: "Fitness Beginner",
        description: "New members looking to build basic fitness routines, requiring high guidance to avoid dropping out.",
        motivation: "Health improvements, lifestyle shift, basic routine guidance.",
        buyingPattern: "Monthly membership renewals, low check-in frequency after initial 30 days.",
        riskLevel: "Critical",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Cross-sell personal training trial packs and trainer check-ins.",
        recommendedStrategy: "Send SMS check-in reminders and free trainer consultation vouchers.",
        whatTheyBuy: "Monthly basic memberships, starter protein packs, water bottles.",
        whyTheyBuy: "To initiate weight loss goals and get help setting up gym machines.",
        whenTheyBuy: "New Year peaks, early summer months, post-holiday weeks.",
        bestCommChannel: "SMS alerts with direct trainer booking links.",
        suggestedCampaign: "Beginner Workout Kickstart (Expected ROI: 3.5x)",
        ageRange: "22 - 40",
        lifestyle: "Sedentary work habits, seeks lifestyle adjustments, low gym confidence.",
        buyingTriggers: "Free trainer sessions, low-friction check-in reminders, milestone achievement badges.",
        preferredProducts: "Basic memberships, trainer consultations",
        aiInsightsTargeting: "Beginners present the highest churn risk. Progress tracking and trainer check-ins in weeks 2-4 boost retention."
      },
      {
        name: "Weight Loss Seeker",
        description: "Cardio-focused members motivated by body transformations and high-energy group fitness classes.",
        motivation: "Weight loss, cardio endurance, group energy, calorie burning.",
        buyingPattern: "3-month and 6-month package checkouts, high group class bookings.",
        riskLevel: "Medium",
        purchaseFrequency: "Quarterly",
        growthOpportunity: "Promote nutrition planner guides and class pre-reservation slots.",
        recommendedStrategy: "Send WhatsApp alerts detailing new Zumba/Spinning slots and dietary templates.",
        whatTheyBuy: "6-month packages, cardio group passes, custom diet plans.",
        whyTheyBuy: "To burn calories in group formats and monitor body fat metrics.",
        whenTheyBuy: "Morning slots, post-work evening hours (5:30 PM - 8:00 PM).",
        bestCommChannel: "WhatsApp messages with class booking buttons.",
        suggestedCampaign: "Body Transformation Challenge (Expected ROI: 4.2x)",
        ageRange: "25 - 50",
        lifestyle: "Balances career with fitness goals, responds well to group motivation and tracking stats.",
        buyingTriggers: "Group class schedules, fat-loss metric transformations, nutrition guides.",
        preferredProducts: "Multi-class passes, body analysis consultations",
        aiInsightsTargeting: "Cardio seekers thrive on community. Promoting group workout times via WhatsApp boosts attendance consistency and reduces subscription lapses."
      },
      {
        name: "Bodybuilder / Enthusiast",
        description: "Advanced strength-training athletes focused on muscle gain, heavy lifting, and supplement catalogs.",
        motivation: "Muscle hypertrophy, strength gains, progressive overload, performance stats.",
        buyingPattern: "Long-term annual membership commitments, high supplement purchase frequency.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Cross-sell premium whey protein isolate, gym accessories, and advanced lifting zones.",
        recommendedStrategy: "Deliver RCS style product catalogs showcasing advanced supplements and lifting belts.",
        whatTheyBuy: "Annual memberships, whey protein, pre-workout tubs, straps.",
        whyTheyBuy: "To access heavy dumbbells, squat racks, and premium recovery equipment.",
        whenTheyBuy: "Off-peak hours, early mornings, late evenings.",
        bestCommChannel: "RCS visual product drop alerts.",
        suggestedCampaign: "Bulk & Strength Supplement Drop (Expected ROI: 4.8x)",
        ageRange: "18 - 35",
        lifestyle: "Highly dedicated to fitness, strict diet cycles, logs workouts daily, gym is a lifestyle.",
        buyingTriggers: "Supplement arrivals, new weight rack additions, wholesale protein sales.",
        preferredProducts: "Whey isolate, pre-workout, weightlifting belts",
        aiInsightsTargeting: "Enthusiasts represent stable annual base revenue. Upselling them on supplements and premium gym apparel drives auxiliary margin growth."
      },
      {
        name: "Corporate Member",
        description: "Employees joining under company-sponsored wellness programs, preferring off-peak hours and convenience.",
        motivation: "Stress relief, company wellness benefits, coworker workout schedules.",
        buyingPattern: "Company-sponsored billings, off-peak midday check-ins.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Promote corporate wellness workshops and coworker challenges.",
        recommendedStrategy: "Send professional emails highlighting executive recovery lounges and post-work slots.",
        whatTheyBuy: "Corporate annual plans, locker renewals, recovery beverage tabs.",
        whyTheyBuy: "To de-stress, take advantage of employee subsidies, and workout with colleagues.",
        whenTheyBuy: "Mid-day lunch hours (12:00 PM - 2:00 PM), early mornings.",
        bestCommChannel: "Corporate HTML newsletters.",
        suggestedCampaign: "Active Corporate Team Challenge (Expected ROI: 4.0x)",
        ageRange: "25 - 45",
        lifestyle: "Desk job, time-crunched, values work-life balance and high-end gym amenities.",
        buyingTriggers: "Corporate reimbursement cycles, team competition notices, executive lounge alerts.",
        preferredProducts: "Corporate annual plans, recovery shakes",
        aiInsightsTargeting: "Corporate bookings have low churn due to company sponsorships. Direct emails featuring recovery facilities secure stable corporate contract renewals."
      }
    ]
  },
  "Real Estate": {
    industry: "Real Estate",
    businessType: "Brokerage Agency",
    businessModel: "Brokerage Commissions",
    primaryMetric: "Commissions",
    secondaryMetric: "Closed Leads",
    revenue: 4500000,
    topCategory: "Residential Sales",
    growthRate: 8,
    riskAreas: ["Interest rate volatility", "Client lead response delays"],
    opportunities: ["First-time buyer workshops", "HNI luxury property portfolios"],
    personas: [
      {
        name: "First-Time Buyer",
        description: "Middle-class families buying their first residential apartment, requiring detailed guidance.",
        motivation: "Family security, asset building, pride of ownership.",
        buyingPattern: "Long search cycles (6-12 months), high consultation volumes, mortgage dependent.",
        riskLevel: "Medium",
        purchaseFrequency: "One-off",
        growthOpportunity: "Affordable housing launches, mortgage pre-approval consultations.",
        recommendedStrategy: "Send WhatsApp property listings matching budget brackets with mortgage calculators.",
        whatTheyBuy: "2BHK apartments, affordable suburban homes, builder floors.",
        whyTheyBuy: "To transition from renting to owning and build stable home environments.",
        whenTheyBuy: "Festival discounts, tax saving quarters, marriage milestones.",
        bestCommChannel: "WhatsApp catalog listings with virtual home tours.",
        suggestedCampaign: "First Home Suburban Showcase (Expected ROI: 3.5x)",
        ageRange: "28 - 40",
        lifestyle: "Salaried employee, handles family logistics, budget-focused.",
        buyingTriggers: "Suburban property drops, mortgage rate cuts, down payment deals.",
        preferredProducts: "Suburban apartments, home loan assistance",
        aiInsightsTargeting: "First-time buyers require high touch. Sending them virtual home videos and cost breakdowns via WhatsApp shortens conversion cycles."
      },
      {
        name: "Real Estate Investor",
        description: "High net-worth individuals buying multiple units for rental yields and capital gains.",
        motivation: "Passive income, portfolio diversification, capital appreciation.",
        buyingPattern: "Rapid decision making, purchase repeat properties, checks commercial returns.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Exclusive pre-launch commercial bookings and HNI priority access.",
        recommendedStrategy: "Deliver email investor reports detailing rental yields and ROI indices.",
        whatTheyBuy: "Studio apartments, commercial offices, pre-rented shops.",
        whyTheyBuy: "To secure inflation-hedged yields and expand passive real estate holdings.",
        whenTheyBuy: "Pre-launch booking windows, year-end property liquidations.",
        bestCommChannel: "Professional analytical emails with financial yield sheets.",
        suggestedCampaign: "High-Yield Commercial Pre-Launch (Expected ROI: 4.8x)",
        ageRange: "35 - 60",
        lifestyle: "Independent HNI, wealth management focus, logs asset performance, transactional buyer.",
        buyingTriggers: "Pre-launch booking discounts, high yield projections, post-rented options.",
        preferredProducts: "Commercial spaces, rental-guarantee studios",
        aiInsightsTargeting: "Investors buy on data, not emotion. Providing detailed cap rate metrics and capital growth history ensures high recurring commissions."
      },
      {
        name: "Luxury Seeker",
        description: "Ultra-HNI buyers looking for premium luxury villas, penthouses, and gated status addresses.",
        motivation: "Status representation, luxury specifications, lifestyle exclusivity.",
        buyingPattern: "Highly selective, focus on privacy and signature designer architects.",
        riskLevel: "Low",
        purchaseFrequency: "One-off",
        growthOpportunity: "Private showroom visits and exclusive villa preview invites.",
        recommendedStrategy: "Send rich RCS cards showing high-res luxury visuals and private viewing bookings.",
        whatTheyBuy: "Premium penthouses, luxury smart villas, farmhouse properties.",
        whyTheyBuy: "To secure exclusive lifestyles, status alignment, and high-end community security.",
        whenTheyBuy: "Private HNI launches, business success milestones.",
        bestCommChannel: "High-fidelity visual RCS invitations.",
        suggestedCampaign: "Signature Gated Villas Showcase (Expected ROI: 4.5x)",
        ageRange: "45 - 65",
        lifestyle: "Business owner or senior executive, premium taste, values privacy and bespoke details.",
        buyingTriggers: "Bespoke developer launches, VIP private preview invitations, smart home luxury features.",
        preferredProducts: "Penthouses, smart luxury villas",
        aiInsightsTargeting: "Luxury seekers buy on branding and exclusivity. RCS cards displaying designer renders and private coordinator callbacks secure elite conversions."
      },
      {
        name: "Family Home Upgrader",
        description: "Growing families upgrading from small apartments to larger layouts close to schooling hubs.",
        motivation: "School proximity, children play zones, larger layouts (3BHK+).",
        buyingPattern: "School calendar dependent, checks neighborhood parks and community amenities.",
        riskLevel: "Medium",
        purchaseFrequency: "One-off",
        growthOpportunity: "Spacious 3BHK/4BHK home showcases near top schooling districts.",
        recommendedStrategy: "Send SMS alerts detailing gated society listings with nearby school rankings.",
        whatTheyBuy: "3BHK apartments, duplex layouts, society flats near schools.",
        whyTheyBuy: "To support growing kids, get close to top schools, and access community amenities.",
        whenTheyBuy: "School summer holiday quarters, mid-year academic sessions.",
        bestCommChannel: "SMS alerts with direct location coordinates.",
        suggestedCampaign: "School District Gated Homes (Expected ROI: 3.8x)",
        ageRange: "35 - 50",
        lifestyle: "Working parent, schedules family transport, values community security and kids facilities.",
        buyingTriggers: "Proximity to schools, society park reviews, ready-to-move-in updates.",
        preferredProducts: "3BHK apartments, society builder floors",
        aiInsightsTargeting: "Upgraders convert fast when school schedules align. Highlighting school bus routes and playground amenities in SMS ads drives click-throughs."
      }
    ]
  },
  "Hospital": {
    industry: "Hospital",
    businessType: "Healthcare Provider",
    businessModel: "Consultations & Outpatient Fees",
    primaryMetric: "Patient Visits",
    secondaryMetric: "Bed Occupancy",
    revenue: 5800000,
    topCategory: "Outpatient Consults",
    growthRate: 5,
    riskAreas: ["Outpatient follow-up appointment leakage", "Emergency room queue wait times"],
    opportunities: ["Telemedicine package extensions", "Preventative annual screening thalis"],
    personas: [
      {
        name: "Chronic Care Patient",
        description: "Elderly patients requiring regular, monthly doctor checkups and long-term diagnostic tracking.",
        motivation: "Health stability, chronic disease control, consistent medical support.",
        buyingPattern: "Monthly consultation checkouts, high diagnostic lab test frequency.",
        riskLevel: "Low",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Cross-sell monthly home diagnostics and customized medicine delivery packages.",
        recommendedStrategy: "Send WhatsApp follow-up reminders with direct slot booking links.",
        whatTheyBuy: "Monthly cardiologist consults, diabetes panels, kidney panels.",
        whyTheyBuy: "To manage chronic ailments and maintain continuous vital monitoring.",
        whenTheyBuy: "Consistent monthly schedules, post-diagnostic test releases.",
        bestCommChannel: "WhatsApp check-ins with one-click booking prompts.",
        suggestedCampaign: "Chronic Care Monthly Wellness Check (Expected ROI: 4.2x)",
        ageRange: "50+",
        lifestyle: "Retired, health-conscious, logs prescriptions, values doctor consistency.",
        buyingTriggers: "WhatsApp booking prompts, prescription refills, test report updates.",
        preferredProducts: "Doctor consultations, diagnostic panels",
        aiInsightsTargeting: "Chronic patients are highly loyal but sensitive to booking hassle. WhatsApp reminders containing direct slot selectors capture repeat visit pipelines."
      },
      {
        name: "Expectant Parent",
        description: "Maternity patients seeking high-care prenatal consultations, ultrasound panels, and delivery suites.",
        motivation: "Safe delivery, baby health, maternity suite comfort.",
        buyingPattern: "Structured 9-month prenatal consult cycles, high premium ward booking rates.",
        riskLevel: "Low",
        purchaseFrequency: "Structured",
        growthOpportunity: "Bundle maternity packages with post-natal care and pediatrician checkups.",
        recommendedStrategy: "Deliver rich RCS updates detailing premium maternity ward amenities and suite tours.",
        whatTheyBuy: "Prenatal ultrasound thalis, delivery suite bookings, baby packages.",
        whyTheyBuy: "To secure safe maternity procedures and access boutique post-natal services.",
        whenTheyBuy: "Prenatal cycle milestones, early pregnancy confirmation.",
        bestCommChannel: "RCS visual ward previews and suite booklets.",
        suggestedCampaign: "Premium Maternity Suite Booking (Expected ROI: 4.5x)",
        ageRange: "25 - 40",
        lifestyle: "Working professional, expecting family expansion, prioritizes hospital comfort.",
        buyingTriggers: "Ultrasound milestone check-ins, premium ward video guides, pediatrician recommendations.",
        preferredProducts: "Maternity packages, suite bookings",
        aiInsightsTargeting: "Maternity is a key gateway to family lifetime loyalty. Promoting premium comfort suites with visual RCS content yields high ward conversions."
      },
      {
        name: "Annual Health Screener",
        description: "Health-focused individuals who book preventive diagnostic checkups once a year.",
        motivation: "Preventative health checks, corporate health benefits, peace of mind.",
        buyingPattern: "Once-a-year package bookings, low interaction between checkups.",
        riskLevel: "High",
        purchaseFrequency: "Annually",
        growthOpportunity: "Promote age-specific advanced screening blocks (e.g., Cardiac screening).",
        recommendedStrategy: "Deliver email reminders with birthday wellness discounts and booking blocks.",
        whatTheyBuy: "Executive health screenings, cardiac screenings, fitness wellness blocks.",
        whyTheyBuy: "To maintain early wellness detection and submit corporate health vouchers.",
        whenTheyBuy: "Birthday months, corporate year-end validation months.",
        bestCommChannel: "Professional HTML email screening reminders.",
        suggestedCampaign: "Annual Preventive Screening Reminder (Expected ROI: 3.8x)",
        ageRange: "30 - 60",
        lifestyle: "Corporate career, healthy lifestyle goals, relies on scheduling alerts.",
        buyingTriggers: "Annual anniversary triggers, corporate policy deadlines, birthday offers.",
        preferredProducts: "Screening packages, blood diagnostic panels",
        aiInsightsTargeting: "Screeners represent high customer churn if not nudged. Email reminders matching their anniversary month are highly effective at driving conversions."
      },
      {
        name: "Emergency/Walk-in",
        description: "Accidental or urgent-care patients checking in for acute health procedures, low predictability.",
        motivation: "Immediate treatment, emergency response, expert surgery.",
        buyingPattern: "Accidental walk-ins, emergency room admission sequences.",
        riskLevel: "High",
        purchaseFrequency: "One-off",
        growthOpportunity: "Cross-sell outpatient post-discharge care and physical therapy consults.",
        recommendedStrategy: "Send SMS discharge summaries with physical therapy appointment blocks.",
        whatTheyBuy: "Emergency procedures, acute fracture treatments, diagnostic scans.",
        whyTheyBuy: "To treat immediate accidents and secure emergency orthopedic/surgical relief.",
        whenTheyBuy: "Unpredictable accident hours, acute symptom flare-ups.",
        bestCommChannel: "Direct SMS text notifications with local clinic maps.",
        suggestedCampaign: "Post-Discharge Rehabilitation Booking (Expected ROI: 3.2x)",
        ageRange: "18 - 70",
        lifestyle: "General public, seeks rapid emergency relief, low brand connection.",
        buyingTriggers: "Discharge guidelines, home-care prescription updates, rehab recommendations.",
        preferredProducts: "Emergency procedures, follow-up consults",
        aiInsightsTargeting: "Walk-ins have low initial brand loyalty. SMS discharge templates highlighting follow-up clinics convert emergency admissions into loyal outpatients."
      }
    ]
  },
  "Travel Agency": {
    industry: "Travel Agency",
    businessType: "Travel Provider",
    businessModel: "Tour Bookings & Packages",
    primaryMetric: "Bookings",
    secondaryMetric: "Customer LTV",
    revenue: 2100000,
    topCategory: "International Tours",
    growthRate: 22,
    riskAreas: ["Off-season tour booking drops", "Refund coordination overheads"],
    opportunities: ["Workcation long-stay packages", "Honeymoon signature tours"],
    personas: [
      {
        name: "Backpacker / Budget",
        description: "Young travelers looking for affordable group tours, hostel bookings, and low-cost adventures.",
        motivation: "Budget travel, social experiences, unique adventure logs.",
        buyingPattern: "Spontaneous booking peaks, highly discount-sensitive, uses early-bird codes.",
        riskLevel: "High",
        purchaseFrequency: "Bi-weekly",
        growthOpportunity: "Promote budget weekend group treks and hostel bundle vouchers.",
        recommendedStrategy: "Send WhatsApp alerts detailing budget weekend tour vacancies.",
        whatTheyBuy: "Group tour packages, hostel beds, economy bus/train bookings.",
        whyTheyBuy: "To explore new destinations within a tight pocket limit and meet peer backpackers.",
        whenTheyBuy: "Holiday weekends, college semester breaks, early summer months.",
        bestCommChannel: "WhatsApp group booking alerts.",
        suggestedCampaign: "Budget Weekend Adventure Drop (Expected ROI: 3.5x)",
        ageRange: "18 - 30",
        lifestyle: "Student or early career, adventure seeker, logs travel on social media.",
        buyingTriggers: "Early-bird coupon codes, group booking discounts, trending social destination reels.",
        preferredProducts: "Hostel vouchers, group tours",
        aiInsightsTargeting: "Budget travelers share experiences organically. WhatsApp group vouchers with group-buy discounts generate rapid word-of-mouth booking peaks."
      },
      {
        name: "Family Vacationer",
        description: "Families booking comprehensive all-inclusive packages close to child-friendly attractions.",
        motivation: "Hassle-free bookings, kid amenities, comfortable travel routes.",
        buyingPattern: "Structured school holiday bookings (summer/winter breaks), high thali/meal plan bookings.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Cross-sell premium resort upgrades and local sightseeing thalis.",
        recommendedStrategy: "Send high-fidelity RCS brochures displaying premium family resort pools and itineraries.",
        whatTheyBuy: "All-inclusive resorts, family flight packages, guided private tours.",
        whyTheyBuy: "To secure stress-free family leisure time without booking logistics overheads.",
        whenTheyBuy: "Summer vacations, Diwali holidays, Christmas-New Year quarters.",
        bestCommChannel: "RCS visual travel brochures with booking buttons.",
        suggestedCampaign: "Summer Family Resort Escape (Expected ROI: 4.5x)",
        ageRange: "30 - 55",
        lifestyle: "Working parent, schedules travel logistics, prioritizes child-friendly comfort.",
        buyingTriggers: "School holiday schedules, luxury resort visual tour reels, all-inclusive price packages.",
        preferredProducts: "Resort packages, private tours",
        aiInsightsTargeting: "Family vacations represent the highest travel spends. Visual RCS brochures showcasing kids pools and hassle-free transit convert annual family packages fast."
      },
      {
        name: "Luxury Honeymooner",
        description: "Newlyweds seeking bespoke romantic villas, private beach stays, and signature tour itineraries.",
        motivation: "Romance, premium luxury, lifetime memories, Instagram-worthy settings.",
        buyingPattern: "Occasional high-value bookings, prioritizes customization over cost.",
        riskLevel: "Low",
        purchaseFrequency: "One-off",
        growthOpportunity: "Bespoke honeymoon upgrades (e.g., private yacht dinners, couples spa).",
        recommendedStrategy: "Deliver professional email travel booklets highlighting luxury boutique villas.",
        whatTheyBuy: "Luxury overwater villas, couples massage vouchers, private yacht dinners.",
        whyTheyBuy: "To celebrate their marriage in elite, high-touch luxury settings.",
        whenTheyBuy: "Wedding season months (November - February).",
        bestCommChannel: "Bespoke travel counselor email templates.",
        suggestedCampaign: "Bespoke Maldives Honeymoon Collection (Expected ROI: 4.8x)",
        ageRange: "24 - 35",
        lifestyle: "HNI professional, planning wedding milestones, values personal counselor checkouts.",
        buyingTriggers: "Private villa video tours, customized couples thali guides, private transit confirmations.",
        preferredProducts: "Overwater villas, private yacht dinners",
        aiInsightsTargeting: "Honeymooners are high-margin, low-price-sensitive leads. Providing high-end digital booklets with personal coordinator help secures premium package bookings."
      },
      {
        name: "Corporate Business Traveler",
        description: "Frequent corporate flyers booking business class travel, corporate hotels, and seminar slots.",
        motivation: "Convenience, business facilities, express boarding, loyalty points.",
        buyingPattern: "Frequent weekly/monthly bookings, corporate account invoicing.",
        riskLevel: "Low",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Cross-sell weekend executive staycations and business lounge keys.",
        recommendedStrategy: "Send SMS notifications highlighting express check-ins and business hotel rooms.",
        whatTheyBuy: "Business flights, corporate hotels, conference hall pre-bookings.",
        whyTheyBuy: "To attend business reviews, client meetings, and industry seminars.",
        whenTheyBuy: "Workdays, business event seasons.",
        bestCommChannel: "SMS alerts with express booking confirmations.",
        suggestedCampaign: "Executive Business Flight & Stay (Expected ROI: 4.0x)",
        ageRange: "28 - 60",
        lifestyle: "Fast-paced corporate professional, frequent flyer, logs company expenses.",
        buyingTriggers: "Lounge key coupons, corporate booking discounts, express booking slots.",
        preferredProducts: "Business hotel slots, lounge passes",
        aiInsightsTargeting: "Business travelers value time above all. SMS notifications containing one-click express booking prompts drive repeat business travel volume."
      }
    ]
  },
  "Electronics Store": {
    industry: "Electronics Store",
    businessType: "Electronics Retailer",
    businessModel: "Retail Sales & Warranties",
    primaryMetric: "Device Sales",
    secondaryMetric: "Warranty Claims",
    revenue: 3200000,
    topCategory: "Smart Accessories & Audio",
    growthRate: 14,
    riskAreas: ["Online marketplace price matching", "Stale inventory depreciation"],
    opportunities: ["Extended warranty packages", "Student device bundles"],
    personas: [
      {
        name: "Tech Early Adopter",
        description: "Flagship gadget enthusiasts who buy new devices on release day, motivated by specs.",
        motivation: "Cutting-edge technology, product specifications, status, pre-orders.",
        buyingPattern: "High-value purchase cycles, logs tech specs, buys flagship devices immediately.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Pre-order VIP invitations, trade-in exchange upgrades.",
        recommendedStrategy: "Deploy RCS visual cards showing new device pre-order specifications.",
        whatTheyBuy: "Flagship smartphones, premium noise-cancelling headphones, high-end laptops.",
        whyTheyBuy: "To hold the latest technological gear and benchmark processing speeds.",
        whenTheyBuy: "Launch day drop windows, festival release peaks.",
        bestCommChannel: "RCS visual spec-sheets and launch buttons.",
        suggestedCampaign: "Flagship Device VIP Pre-orders (Expected ROI: 4.5x)",
        ageRange: "18 - 35",
        lifestyle: "Tech enthusiast, active gamer/builder, reads specs, early tech adapter.",
        buyingTriggers: "Spec sheet updates, pre-order countdowns, trade-in exchange bonuses.",
        preferredProducts: "Smartphones, premium headphones, pro laptops",
        aiInsightsTargeting: "Early adopters convert on details. Delivering visual RCS spec sheets with pre-order booking triggers locks in flagship device allocations."
      },
      {
        name: "Value Gadget Hunter",
        description: "Mid-range gadget buyers who compare pricing models and track clearance discount events.",
        motivation: "Product value-for-money, discount alerts, bundle deals.",
        buyingPattern: "Competitor price comparisons, highly discount-sensitive, buys mid-range specs.",
        riskLevel: "Medium",
        purchaseFrequency: "Quarterly",
        growthOpportunity: "Bundle accessory packages (e.g., case + screen guard + charger).",
        recommendedStrategy: "Send WhatsApp messages detailing clearance accessory bundle discounts.",
        whatTheyBuy: "Mid-range smartphones, bluetooth earbuds, power banks, smartwatch bands.",
        whyTheyBuy: "To secure reliable everyday tech operations without paying premium flagship costs.",
        whenTheyBuy: "Mid-season clearance events, holiday shopping weeks.",
        bestCommChannel: "WhatsApp alerts with bundle discount images.",
        suggestedCampaign: "Clearance Accessory Bundle Drop (Expected ROI: 4.2x)",
        ageRange: "21 - 45",
        lifestyle: "Budget-focused, logs product reviews, compares online listings.",
        buyingTriggers: "Price cuts, bundle discount codes, free warranty upgrades.",
        preferredProducts: "Earbuds, power banks, mid-range phones",
        aiInsightsTargeting: "Value hunters want immediate pricing proof. WhatsApp ads containing bundle discounts convert price-sensitive shoppers."
      },
      {
        name: "Work-from-Home Professional",
        description: "Professionals seeking home office upgrades, monitor mounts, and pro desktop peripherals.",
        motivation: "Desk ergonomics, productivity speed, home office comfort.",
        buyingPattern: "Corporate tax-saving quarters, corporate subsidy allocations.",
        riskLevel: "Low",
        purchaseFrequency: "Bi-annually",
        growthOpportunity: "Home office bundles (e.g., keyboard + mouse + mousepad).",
        recommendedStrategy: "Deliver professional emails showcasing ergonomic keyboards and monitor stands.",
        whatTheyBuy: "Mechanical keyboards, ergonomic mice, monitor mounts, desktop USB docks.",
        whyTheyBuy: "To improve typing comfort, double monitor workspace speeds, and desk layout aesthetics.",
        whenTheyBuy: "WFH subsidy months, corporate tax-saving quarters.",
        bestCommChannel: "Sleek professional HTML email edits.",
        suggestedCampaign: "Ultimate WFH Desk Upgrades (Expected ROI: 4.0x)",
        ageRange: "25 - 50",
        lifestyle: "Work-from-home career, prioritizes productivity, logs desktop specifications.",
        buyingTriggers: "WFH reimbursement deadlines, desktop comfort reviews, bundle discounts.",
        preferredProducts: "Ergonomic mice, mechanical keyboards, monitor stands",
        aiInsightsTargeting: "WFH buyers log expenses. Email templates featuring WFH thali bundles with direct receipt generation links speed up purchase decisions."
      },
      {
        name: "Gift Shopper",
        description: "Holiday and birthday shoppers looking for gadgets and audio accessories for friends/family.",
        motivation: "Gift packaging, warranty reliability, simple choices.",
        buyingPattern: "Occasional holiday peaks (Diwali, Christmas), buys gift boxes.",
        riskLevel: "High",
        purchaseFrequency: "Occasion-based",
        growthOpportunity: "Gift box wrapping, customized birthday voucher upgrades.",
        recommendedStrategy: "Send SMS alerts detailing festive audio gadget gift box selections.",
        whatTheyBuy: "Portable Bluetooth speakers, smartwatches, decorative lighting pads.",
        whyTheyBuy: "To buy reliable electronic gifts for siblings, parents, or coworkers.",
        whenTheyBuy: "Festive seasons, birthday months, graduation weeks.",
        bestCommChannel: "SMS alerts with direct gift box selection lists.",
        suggestedCampaign: "Festive Gadget Gift Box Deals (Expected ROI: 3.8x)",
        ageRange: "30 - 60",
        lifestyle: "Family-centric, logs family birthdays, prioritizes quick gift selections.",
        buyingTriggers: "Gift wrapping availability, occasion countdowns, easy exchange warranties.",
        preferredProducts: "Bluetooth speakers, smartwatches, LED strips",
        aiInsightsTargeting: "Gift buyers value convenience over product specs. SMS ads offering pre-packaged gift boxes with simple exchange vouchers convert fast."
      }
    ]
  },
  "Coaching Institute": {
    industry: "Coaching Institute",
    businessType: "Educational Center",
    businessModel: "Course Tuition Fees",
    primaryMetric: "Enrollments",
    secondaryMetric: "Class Attendance",
    revenue: 850000,
    topCategory: "Exam Preparation",
    growthRate: 20,
    riskAreas: ["Mid-term course dropouts", "Negative parental reviews"],
    opportunities: ["Online test prep extensions", "Early-bird cohort deals"],
    personas: [
      {
        name: "Competitive Aspirant",
        description: "Intensive exam prep students aiming for top medical/engineering entries, high pressure.",
        motivation: "Exam success, university admissions, rank tracking.",
        buyingPattern: "Annual course subscriptions, high test book checkouts, mock exam entries.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Advanced mock test series and counselor consultations.",
        recommendedStrategy: "Send WhatsApp messages containing exam schedules and mock test series links.",
        whatTheyBuy: "Annual exam courses, mock test packs, formula sheet notebooks.",
        whyTheyBuy: "To crack national entrance tests and secure premium university seats.",
        whenTheyBuy: "Course launch months, pre-exam prep quarters.",
        bestCommChannel: "WhatsApp messages with class scheduling links.",
        suggestedCampaign: "National Mock Test Series Access (Expected ROI: 4.5x)",
        ageRange: "15 - 22",
        lifestyle: "Student, high study hours, checks rank scores, stress-motivated.",
        buyingTriggers: "Exam countdowns, syllabus checklists, mock score analysis updates.",
        preferredProducts: "Exam courses, mock test packs",
        aiInsightsTargeting: "Aspirants are data-centric. WhatsApp updates containing mock test schedules and score analyses drive course enrollment."
      },
      {
        name: "Career Switcher",
        description: "Working professionals attending evening/weekend coding and business bootcamps.",
        motivation: "Career transition, salary hikes, upskilling benchmarks.",
        buyingPattern: "Installment-based bootcamps, high resume review requests.",
        riskLevel: "Medium",
        purchaseFrequency: "One-off",
        growthOpportunity: "Placement portal additions and corporate mentorship check-ins.",
        recommendedStrategy: "Send professional emails highlighting bootcamp alumni salaries and placement records.",
        whatTheyBuy: "Full-stack bootcamps, resume review packs, mock interviewer slots.",
        whyTheyBuy: "To pivot from low-growth jobs to corporate tech roles.",
        whenTheyBuy: "New Year career resolutions, appraisal cycles.",
        bestCommChannel: "Sleek professional HTML emails with syllabus brochures.",
        suggestedCampaign: "Upskill Full-Stack Bootcamp Intake (Expected ROI: 4.2x)",
        ageRange: "23 - 35",
        lifestyle: "Working professional, evening student, time-crunched, convenience-motivated.",
        buyingTriggers: "Alumni salary statistics, job portal partnerships, EMI installment options.",
        preferredProducts: "Coding bootcamps, mock interview sessions",
        aiInsightsTargeting: "Switchers value ROI. Email campaigns containing clear bootcamp placement rates and EMI plans convert working professionals."
      },
      {
        name: "High School Academic",
        description: "Secondary school students taking evening board exam tutoring, parent payer.",
        motivation: "School grades, board exam targets, parental approval.",
        buyingPattern: "Monthly school tuition cycles, high parent-teacher coordination.",
        riskLevel: "Medium",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Home assignment booklets and science laboratory modules.",
        recommendedStrategy: "Deliver SMS metrics to parents detailing grade updates and revision schedules.",
        whatTheyBuy: "Math/Science tuition packages, board exam booklets, parent consultation packs.",
        whyTheyBuy: "To clear board exams and maintain high school grade rankings.",
        whenTheyBuy: "Academic term openings, pre-board exam months.",
        bestCommChannel: "SMS messages directed to parent mobile numbers.",
        suggestedCampaign: "Board Exam Revision Crash Course (Expected ROI: 3.8x)",
        ageRange: "13 - 18",
        lifestyle: "School student, manages school homework, relies on parent payments.",
        buyingTriggers: "Term report cards, board exam count downs, parental review sessions.",
        preferredProducts: "Tuition packages, revision booklets",
        aiInsightsTargeting: "Parents make the purchasing decision. Sending SMS grade updates and board prep countdowns drives parent enrollment conversions."
      },
      {
        name: "Hobbyist Learner",
        description: "Part-time students taking short courses in creative styling, design, or languages.",
        motivation: "Personal growth, hobby development, light learning cycles.",
        buyingPattern: "Short 4-week course checkouts, self-paced modules.",
        riskLevel: "High",
        purchaseFrequency: "Quarterly",
        growthOpportunity: "Promote beginner combo courses and peer certification passes.",
        recommendedStrategy: "Send visual RCS brochures showcasing creative student portfolios and certificate drops.",
        whatTheyBuy: "Chic design workshops, language basics, photography crash courses.",
        whyTheyBuy: "To learn design parameters and display certification badges on LinkedIn.",
        whenTheyBuy: "Weekend holiday quarters, evening hobby hours.",
        bestCommChannel: "RCS visual course portfolios with booking links.",
        suggestedCampaign: "Creative Design Weekend Bootcamp (Expected ROI: 4.0x)",
        ageRange: "20 - 50",
        lifestyle: "Curious, values self-paced learning, logs creative hobbies.",
        buyingTriggers: "Workshop videos, creative certificate drops, early bird offers.",
        preferredProducts: "Design workshops, language classes",
        aiInsightsTargeting: "Hobbyists drop out easily. Visual RCS ads containing portfolio showcases and quick certificates keep them engaged and buying."
      }
    ]
  },
  "SaaS Startup": {
    industry: "SaaS Startup",
    businessType: "Software-as-a-Service",
    businessModel: "Subscription License Fees",
    primaryMetric: "ARR",
    secondaryMetric: "Seat Utilization",
    revenue: 2600000,
    topCategory: "Enterprise Plans",
    growthRate: 35,
    riskAreas: ["Seat utilization leakage", "SLA support ticket queue delays"],
    opportunities: ["Usage-based credits expansion", "Developer SDK integrations"],
    personas: [
      {
        name: "CTO / Enterprise Buyer",
        description: "Corporate technical decision makers focused on security compliance, team scaling, and SLAs.",
        motivation: "Data security compliance, API reliability, SLA guarantees, centralized invoicing.",
        buyingPattern: "Annual enterprise billing, formal contract negotiations, high support ticket prioritization.",
        riskLevel: "Low",
        purchaseFrequency: "Annually",
        growthOpportunity: "Add-on security audits, custom single-sign-on (SSO) packages.",
        recommendedStrategy: "Deliver analytical HTML emails showcasing system uptime stats and SOC2 compliance.",
        whatTheyBuy: "Enterprise annual subscriptions, dedicated support nodes, custom SSO integrations.",
        whyTheyBuy: "To scale software infrastructure safely across departments and guarantee system security.",
        whenTheyBuy: "Corporate budget quarters, system audit periods.",
        bestCommChannel: "Direct account executive email newsletters.",
        suggestedCampaign: "Enterprise SOC2 Upgrade & SSO (Expected ROI: 4.8x)",
        ageRange: "35 - 55",
        lifestyle: "Executive, focuses on tech infrastructure, logs security stats, HNI buyer.",
        buyingTriggers: "Compliance deadlines, team seat saturation, system reliability reports.",
        preferredProducts: "Enterprise plans, SSO add-ons",
        aiInsightsTargeting: "Enterprise buyers need security proof. Sending them SOC2 compliance materials and uptime reports via email ensures renewals."
      },
      {
        name: "Developer / Builder",
        description: "Technical builders who integrate API keys, customize mobile SDKs, and build custom webhooks.",
        motivation: "API documentation, SDK ease-of-use, developer keys, deployment speeds.",
        buyingPattern: "Usage-based credit checkouts, custom plan expansions, sandbox usage peaks.",
        riskLevel: "Medium",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Usage credit bundle sales, advanced SDK premium integrations.",
        recommendedStrategy: "Send SMS alerts detailing developer API credit limits and dashboard statistics.",
        whatTheyBuy: "Usage credit bundles, mobile SDK keys, premium API keys.",
        whyTheyBuy: "To integrate features fast, bypass offline backend coding, and check database keys.",
        whenTheyBuy: "Project sprint launches, late night coding peaks.",
        bestCommChannel: "SMS alerts containing direct credit recharge links.",
        suggestedCampaign: "Developer API Credit Boost (Expected ROI: 4.5x)",
        ageRange: "20 - 35",
        lifestyle: "Software builder, sandbox user, tech-motivated.",
        buyingTriggers: "Credit threshold warnings, new SDK key releases, sprint deadlines.",
        preferredProducts: "API credit packs, developer subscriptions",
        aiInsightsTargeting: "Developers want frictionless billing. SMS alerts triggered when usage hits 80% containing direct credit top-up links prevent downtime."
      },
      {
        name: "SMB Operations Head",
        description: "Small business managers looking for time-saving software integrations and dashboard reports.",
        motivation: "Operational efficiency, team workspace sharing, simple tool integrations.",
        buyingPattern: "Monthly recurring credit card billings, self-serve onboarding.",
        riskLevel: "High",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Integrate third-party app plugins and export-automation addons.",
        recommendedStrategy: "Send WhatsApp alerts detailing new tool integrations and time-saving features.",
        whatTheyBuy: "Team plans, analytics dashboards, CSV export integrations.",
        whyTheyBuy: "To automate team workflows and run business reports without manual sheet edits.",
        whenTheyBuy: "Month-end reporting cycles, new employee onboarding weeks.",
        bestCommChannel: "WhatsApp tutorials with click-to-integrate buttons.",
        suggestedCampaign: "Team Workspace Integrations Blast (Expected ROI: 4.2x)",
        ageRange: "25 - 45",
        lifestyle: "SMB operator, multi-tasker, logs task times, values time-saving hacks.",
        buyingTriggers: "Integration announcements, employee seat additions, month-end report counts.",
        preferredProducts: "Team subscriptions, reporting addons",
        aiInsightsTargeting: "SMBs drop out if setup is complex. WhatsApp tutorials with direct integration links drive early feature adoption and lock in retention."
      },
      {
        name: "Trial Sign-up / Explorer",
        description: "Freemium users exploring software capabilities, high risk of leaving after trial ends.",
        motivation: "Free trial access, basic feature testing, self-paced exploration.",
        buyingPattern: "Freemium signups, low session counts after initial 3 days.",
        riskLevel: "Critical",
        purchaseFrequency: "Monthly",
        growthOpportunity: "Upsell to professional starter subscriptions with trial extension deals.",
        recommendedStrategy: "Deliver visual RCS carousels highlighting core features and trial discount codes.",
        whatTheyBuy: "Free trial plans, basic starter plans.",
        whyTheyBuy: "To test software integrations before committing corporate budgets.",
        whenTheyBuy: "Ad-hoc task spikes, early research quarters.",
        bestCommChannel: "RCS visual checklists and trial coupons.",
        suggestedCampaign: "Trial Professional Upgrade Deal (Expected ROI: 3.8x)",
        ageRange: "18 - 40",
        lifestyle: "Explorer, budget-conscious, logs multiple SaaS trials.",
        buyingTriggers: "Trial expiration warnings, core feature activation badges, coupon codes.",
        preferredProducts: "Starter subscriptions, upgrade coupons",
        aiInsightsTargeting: "Explorers need prompt activation. RCS visual checklists showing setup progress and early coupon codes boost conversion to paid plans."
      }
    ]
  }
};
